apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    env: sandbox
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.22.4
  install:
    createNamespace: true
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
  interval: 5m
  rollback:
    cleanupOnFail: true
    disableHooks: false
  targetNamespace: istio-system
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    env: sandbox
  name: istio-ingress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.22.4
  dependsOn:
  - name: istio-base
    namespace: flux-system
  - name: istiod
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
  interval: 5m
  rollback:
    cleanupOnFail: true
    disableHooks: false
  targetNamespace: istio-ingress
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
  values:
    nameOverride: istio-ingressgateway
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    podAnnotations:
      sidecar.istio.io/inject: "false"
    service:
      externalTrafficPolicy: Local
      ports:
      - name: status-port
        nodePort: 31521
        port: 15021
        targetPort: 15021
      - name: http2
        nodePort: 30080
        port: 80
        targetPort: 8080
      - name: https
        nodePort: 30443
        port: 443
        targetPort: 8443
      type: NodePort
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    env: sandbox
  name: istiod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.22.4
  dependsOn:
  - name: istio-base
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
  interval: 5m
  rollback:
    cleanupOnFail: true
    disableHooks: false
  targetNamespace: istio-system
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
    timeout: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    env: sandbox
  name: istio
  namespace: flux-system
spec:
  interval: 30m
  timeout: 1m
  url: https://istio-release.storage.googleapis.com/charts
