apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 30m
  url: https://istio-release.storage.googleapis.com/charts]
  timeout: 1m
